# Generated by Django 3.1.3 on 2020-11-09 05:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now=True)),
                ('shoplist', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.profile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
